spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client_id
            client-secret: secret_id
            scope:
              - email
              - profile

authentication:
  native-secret: secret
